version: '3.8'

services:
  web:
    build:
      context: docker/apache
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "1234:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: crud_php
      MYSQL_USER: pma